// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link"; // 🔹 추가
import "./globals.css";

// 🔹 폰트 설정 유지
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 🔹 메타데이터 유지
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 🔹 레이아웃
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-text`}
      >
        {/* 🔹 상단 고정 네비게이션 바 */}
        <nav className="w-full bg-white shadow-md p-4 sticky top-0 z-50">
          {/* <div className="max-w-7xl mx-auto flex gap-6 items-center text-sm font-semibold text-gray-700"> */}
          <div className="max-w-7xl mx-auto flex gap-6 items-center text-lg font-semibold text-black">
            <Link href="/" className="hover:text-blue-500">🚀 BuildU</Link>
            <Link href="/upload" className="hover:text-blue-500">CV Feedback</Link>
            <Link href="/review" className="hover:text-blue-500">Results</Link>
            <Link href="/humanizer" className="hover:text-blue-500">Humanizer</Link>
            <Link href="/compare" className="hover:text-blue-500">Text Compare</Link>
            <Link href="/ielts" className="hover:text-blue-500">IELTS</Link>
          </div>
        </nav>

        {/* 🔹 페이지 내용 */}
        <main className="">{children}</main>
      </body>
    </html>
  );
}
